Update README.md re: Netlify CLI
netlify/gotrue-js pull request #234
Opened 2020-12-03 13:04 UTC by ttntm

Added a note for Netlify CLI users; functions containing admin methods need to be deployed in order to work as intended.

2020-12-03 15:43 UTC, erezrokah requested changes
Thanks @ttntm, great addition. I suggested a small change, please let me know what you think.

2020-12-03 15:43 UTC, erezrokah commented on README.md
> +For users of [Netlify CLI](https://github.com/netlify/cli): please note, that functions using admin methods will _not_ work locally - they need to be deployed to your site in order to work as intende
```suggestion
> For users of [Netlify CLI](https://github.com/netlify/cli) - functions using admin methods will _not_ work locally - they need to be deployed to your site in order to work as intended.
```

2020-12-03 16:08 UTC, ttntm commented
Thanks for the improved version, it's better that way.

2020-12-03 16:34 UTC, erezrokah approved these changes

2020-12-03 16:35 UTC, merged

2020-12-07 10:58 UTC, erezrokah commented
:tada: This PR is included in version 0.9.28 :tada:

The release is available on [GitHub release](https://github.com/netlify/gotrue-js/releases/tag/v0.9.28)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: